In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [31]:
data = pd.read_csv('Food_Delivery_Times.csv')
data.head()

,Order_ID,Distance_km,Weather,Traffic_Level,Time_of_Day,Vehicle_Type,Preparation_Time_min,Courier_Experience_yrs,Delivery_Time_min
0,522,7.93,Windy,Low,Afternoon,Scooter,12,1.0,43
1,738,16.42,Clear,Medium,Evening,Bike,20,2.0,84
2,741,9.52,Foggy,Low,Night,Scooter,28,1.0,59
3,661,7.44,Rainy,Medium,Afternoon,Scooter,5,1.0,37
4,412,19.03,Clear,Low,Morning,Bike,16,5.0,68

In [32]:
data.shape

(1000, 9)

In [33]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Order_ID                1000 non-null   int64
 1   Distance_km             1000 non-null   float64
 2   Weather                 970 non-null    object
 3   Traffic_Level           970 non-null    object
 4   Time_of_Day             970 non-null    object
 5   Vehicle_Type            1000 non-null   object
 6   Preparation_Time_min    1000 non-null   int64
 7   Courier_Experience_yrs  970 non-null    float64
 8   Delivery_Time_min       1000 non-null   int64
dtypes: float64(2), int64(3), object(4)
memory usage: 70.4+ KB

In [34]:
data.describe()

,Order_ID,Distance_km,Preparation_Time_min,Courier_Experience_yrs,Delivery_Time_min
count,1000.000000,1000.000000,1000.000000,970.000000,1000.000000
mean,500.500000,10.059970,16.982000,4.579381,56.732000
std,288.819436,5.696656,7.204553,2.914394,22.070915
min,1.000000,0.590000,5.000000,0.000000,8.000000
25%,250.750000,5.105000,11.000000,2.000000,41.000000
50%,500.500000,10.190000,17.000000,5.000000,55.500000
75%,750.250000,15.017500,23.000000,7.000000,71.000000
max,1000.000000,19.990000,29.000000,9.000000,153.000000

In [35]:
data.columns

Index(['Order_ID', 'Distance_km', 'Weather', 'Traffic_Level', 'Time_of_Day',
       'Vehicle_Type', 'Preparation_Time_min', 'Courier_Experience_yrs',
       'Delivery_Time_min'],
      dtype='object')

In [36]:
data.describe(include='object')

       Weather Traffic_Level Time_of_Day Vehicle_Type
count      970           970         970         1000
unique       5             3           4            3
top      Clear        Medium     Morning         Bike
freq       470           390         308          503

In [37]:
data['Time_of_Day'].value_counts()

Time_of_Day
Morning      308
Evening      293
Afternoon    284
Night         85
Name: count, dtype: int64

In [38]:
data['Weather'].value_counts()

Weather
Clear    470
Rainy    204
Foggy    103
Snowy     97
Windy     96
Name: count, dtype: int64

In [39]:
data['Traffic_Level'].value_counts()

Traffic_Level
Medium    390
Low       383
High      197
Name: count, dtype: int64

In [40]:
data['Vehicle_Type'].value_counts()

Vehicle_Type
Bike       503
Scooter    302
Car        195
Name: count, dtype: int64

In [41]:
data.duplicated().sum()

np.int64(0)

In [42]:
data.isnull().sum()

Order_ID                   0
Distance_km                0
Weather                   30
Traffic_Level             30
Time_of_Day               30
Vehicle_Type               0
Preparation_Time_min       0
Courier_Experience_yrs    30
Delivery_Time_min          0
dtype: int64

In [57]:
data_c = data.copy()
data_c['Weather'] = data_c['Weather'].fillna(data['Weather'].mode()[0])

In [58]:
data_c.isnull().sum()

Order_ID                   0
Distance_km                0
Weather                    0
Traffic_Level             30
Time_of_Day               30
Vehicle_Type               0
Preparation_Time_min       0
Courier_Experience_yrs    30
Delivery_Time_min          0
dtype: int64

In [59]:
data_c['Weather'].unique()

array(['Windy', 'Clear', 'Foggy', 'Rainy', 'Snowy'], dtype=object)

In [64]:
data_c['Traffic_Level'].unique()

array(['Low', 'Medium', 'High', nan], dtype=object)

In [72]:
data_drop = data.copy()
data_drop = data_drop.dropna(subset=['Weather', 'Traffic_Level', 'Time_of_Day', 'Courier_Experience_yrs'])

In [73]:
data_drop.isnull().sum()

Order_ID                  0
Distance_km               0
Weather                   0
Traffic_Level             0
Time_of_Day               0
Vehicle_Type              0
Preparation_Time_min      0
Courier_Experience_yrs    0
Delivery_Time_min         0
dtype: int64

In [74]:
data_drop.shape

(883, 9)

In [75]:
data_drop.head()

,Order_ID,Distance_km,Weather,Traffic_Level,Time_of_Day,Vehicle_Type,Preparation_Time_min,Courier_Experience_yrs,Delivery_Time_min
0,522,7.93,Windy,Low,Afternoon,Scooter,12,1.0,43
1,738,16.42,Clear,Medium,Evening,Bike,20,2.0,84
2,741,9.52,Foggy,Low,Night,Scooter,28,1.0,59
3,661,7.44,Rainy,Medium,Afternoon,Scooter,5,1.0,37
4,412,19.03,Clear,Low,Morning,Bike,16,5.0,68

In [79]:
data_drop_c = data_drop.copy()

data_drop_c.head()

,Order_ID,Distance_km,Weather,Traffic_Level,Time_of_Day,Vehicle_Type,Preparation_Time_min,Courier_Experience_yrs,Delivery_Time_min
0,522,7.93,Windy,Low,Afternoon,Scooter,12,1.0,43
1,738,16.42,Clear,Medium,Evening,Bike,20,2.0,84
2,741,9.52,Foggy,Low,Night,Scooter,28,1.0,59
3,661,7.44,Rainy,Medium,Afternoon,Scooter,5,1.0,37
4,412,19.03,Clear,Low,Morning,Bike,16,5.0,68

In [84]:
data_drop_c = data_drop_c.drop('Order_ID', axis=1)

In [85]:
data_drop_c.head()

,Distance_km,Weather,Traffic_Level,Time_of_Day,Vehicle_Type,Preparation_Time_min,Courier_Experience_yrs,Delivery_Time_min
0,7.93,Windy,Low,Afternoon,Scooter,12,1.0,43
1,16.42,Clear,Medium,Evening,Bike,20,2.0,84
2,9.52,Foggy,Low,Night,Scooter,28,1.0,59
3,7.44,Rainy,Medium,Afternoon,Scooter,5,1.0,37
4,19.03,Clear,Low,Morning,Bike,16,5.0,68

In [86]:
data_l = data_drop_c.copy()

In [87]:
data_l = pd.get_dummies(data_l, columns=['Weather', 'Traffic_Level', 'Time_of_Day', 'Vehicle_Type'], drop_first=True, dtype=int)

In [89]:
data_l.head()

,Distance_km,Preparation_Time_min,Courier_Experience_yrs,Delivery_Time_min,Weather_Foggy,Weather_Rainy,Weather_Snowy,Weather_Windy,Traffic_Level_Low,Traffic_Level_Medium,Time_of_Day_Evening,Time_of_Day_Morning,Time_of_Day_Night,Vehicle_Type_Car,Vehicle_Type_Scooter
0,7.93,12,1.0,43,0,0,0,1,1,0,0,0,0,0,1
1,16.42,20,2.0,84,0,0,0,0,0,1,1,0,0,0,0
2,9.52,28,1.0,59,1,0,0,0,1,0,0,0,1,0,1
3,7.44,5,1.0,37,0,1,0,0,0,1,0,0,0,0,1
4,19.03,16,5.0,68,0,0,0,0,1,0,0,1,0,0,0

In [91]:
data_l.info()

<class 'pandas.core.frame.DataFrame'>
Index: 883 entries, 0 to 999
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Distance_km             883 non-null    float64
 1   Preparation_Time_min    883 non-null    int64
 2   Courier_Experience_yrs  883 non-null    float64
 3   Delivery_Time_min       883 non-null    int64
 4   Weather_Foggy           883 non-null    int64
 5   Weather_Rainy           883 non-null    int64
 6   Weather_Snowy           883 non-null    int64
 7   Weather_Windy           883 non-null    int64
 8   Traffic_Level_Low       883 non-null    int64
 9   Traffic_Level_Medium    883 non-null    int64
 10  Time_of_Day_Evening     883 non-null    int64
 11  Time_of_Day_Morning     883 non-null    int64
 12  Time_of_Day_Night       883 non-null    int64
 13  Vehicle_Type_Car        883 non-null    int64
 14  Vehicle_Type_Scooter    883 non-null    int64
dtypes: float64(2), int64(13)
memory usage: 110.4 KB

In [96]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
col = ['Distance_km', 'Preparation_Time_min', 'Courier_Experience_yrs', 'Delivery_Time_min']

df = data_l.copy()
df[col] = scaler.fit_transform(df[col])

In [97]:
df.head()

,Distance_km,Preparation_Time_min,Courier_Experience_yrs,Delivery_Time_min,Weather_Foggy,Weather_Rainy,Weather_Snowy,Weather_Windy,Traffic_Level_Low,Traffic_Level_Medium,Time_of_Day_Evening,Time_of_Day_Morning,Time_of_Day_Night,Vehicle_Type_Car,Vehicle_Type_Scooter
0,-0.373166,-0.691730,-1.246308,-0.622827,0,0,0,1,1,0,0,0,0,0,1
1,1.120143,0.410793,-0.903903,1.279172,0,0,0,0,0,1,1,0,0,0,0
2,-0.093501,1.513315,-1.246308,0.119417,1,0,0,0,1,0,0,0,1,0,1
3,-0.459353,-1.656437,-1.246308,-0.901168,0,1,0,0,0,1,0,0,0,0,1
4,1.579216,-0.140469,0.123312,0.536929,0,0,0,0,1,0,0,1,0,0,0

In [102]:
X = df.drop('Delivery_Time_min', axis=1)
y = df['Delivery_Time_min']
X.head(2)

,Distance_km,Preparation_Time_min,Courier_Experience_yrs,Weather_Foggy,Weather_Rainy,Weather_Snowy,Weather_Windy,Traffic_Level_Low,Traffic_Level_Medium,Time_of_Day_Evening,Time_of_Day_Morning,Time_of_Day_Night,Vehicle_Type_Car,Vehicle_Type_Scooter
0,-0.373166,-0.691730,-1.246308,0,0,0,1,1,0,0,0,0,0,1
1,1.120143,0.410793,-0.903903,0,0,0,0,0,1,1,0,0,0,0

In [103]:
y.head(2)

0   -0.622827
1    1.279172
Name: Delivery_Time_min, dtype: float64

In [104]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [105]:
X_train.shape

(706, 14)

In [106]:
X_test.shape

(177, 14)

In [107]:
y_train.shape

(706,)

In [108]:
y_test.shape

(177,)

In [109]:
df.shape

(883, 15)

In [112]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

lr.fit(X_train, y_train)

LinearRegression()

In [113]:
y_pred_lr = lr.predict(X_test)

In [116]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, root_mean_squared_error

r2 = r2_score(y_test, y_pred_lr)
mae = mean_absolute_error(y_test, y_pred_lr)
mse = mean_squared_error(y_test, y_pred_lr)
rmse = np.sqrt(mse)

print(f"R2 Score: {r2:.2f}")
print(f"Mean Absolute Error: {mae:.2f}")
print(f"Mean Squared Error: {mse:.2f}")
print(f"Root Mean Squared Error: {rmse:.2f}")

R2 Score: 0.83
Mean Absolute Error: 0.25
Mean Squared Error: 0.15
Root Mean Squared Error: 0.38

In [117]:
print("Train Score:", lr.score(X_train, y_train))
print("Test Score :", lr.score(X_test, y_test))

Train Score: 0.7742847300970708
Test Score : 0.8325314582304298

In [118]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(lr, X, y, cv=5, scoring="r2")

print(scores)
print("Average R²:", scores.mean())

[0.69129668 0.86651707 0.82551487 0.74408665 0.77620213]
Average R²: 0.7807234811569825

In [124]:
from sklearn.tree import DecisionTreeRegressor

dt = DecisionTreeRegressor()

dt_model = dt.fit(X_train,y_train)

y_pred_dt = dt_model.predict(X_test)

In [125]:
r2_dt = r2_score(y_test, y_pred_dt)
mae_dt = mean_absolute_error(y_test, y_pred_dt)
mse_dt = mean_squared_error(y_test, y_pred_dt)
rmse_dt = np.sqrt(mse_dt)

dt_scores = cross_val_score(dt, X, y, cv=5, scoring='r2')

print(dt_scores)
print(f"Average R2: {dt_scores.mean()}")
print(f"R2 Score: {r2_dt:.2f}")
print(f"Mean Absolute Error: {mae_dt:.2f}")
print(f"Mean Squared Error: {mse_dt:.2f}")
print(f"Root Mean Squared Error: {rmse_dt:.2f}")

[0.41815685 0.61446038 0.55307125 0.31301672 0.25197555]
Average R2: 0.4301361500641702
R2 Score: 0.49
Mean Absolute Error: 0.47
Mean Squared Error: 0.45
Root Mean Squared Error: 0.67

In [126]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor()

rf_model = rf.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

In [127]:
r2_rf = r2_score(y_test, y_pred_rf)
mae_rf = mean_absolute_error(y_test, y_pred_rf)
mse_rf = mean_squared_error(y_test, y_pred_rf)
rmse_rf = np.sqrt(mse_rf)

rf_scores = cross_val_score(rf, X, y, cv=5, scoring='r2')

print(rf_scores)
print(f"Average R2: {rf_scores.mean()}")
print(f"R2 Score: {r2_rf:.2f}")
print(f"Mean Absolute Error: {mae_rf:.2f}")
print(f"Mean Squared Error: {mse_rf:.2f}")
print(f"Root Mean Squared Error: {rmse_rf:.2f}")

[0.62231132 0.77518771 0.79149365 0.66487625 0.70224608]
Average R2: 0.7112230036692064
R2 Score: 0.77
Mean Absolute Error: 0.31
Mean Squared Error: 0.21
Root Mean Squared Error: 0.45

In [128]:
from xgboost import XGBRegressor

xr = XGBRegressor()
xr_model = xr.fit(X_train, y_train)

In [129]:
y_pred_xr = xr_model.predict(X_test)

In [130]:
r2_xr = r2_score(y_test, y_pred_xr)
mae_xr = mean_absolute_error(y_test, y_pred_xr)
mse_xr = mean_squared_error(y_test, y_pred_xr)
rmse_xr = np.sqrt(mse_xr)

xr_scores = cross_val_score(xr, X, y, cv=5, scoring='r2')

print(xr_scores)
print(f"Average R2: {xr_scores.mean()}")
print(f"R2 Score: {r2_xr:.2f}")
print(f"Mean Absolute Error: {mae_xr:.2f}")
print(f"Mean Squared Error: {mse_xr:.2f}")
print(f"Root Mean Squared Error: {rmse_xr:.2f}")

[0.61464894 0.71177246 0.73222035 0.67681165 0.64981407]
Average R2: 0.6770534926127414
R2 Score: 0.71
Mean Absolute Error: 0.34
Mean Squared Error: 0.25
Root Mean Squared Error: 0.50

In [ ]:
import joblib

joblib.dump(lr, "delivery_time_model.pkl")
joblib.dump(data_l, 'data_encoding.pkl')
joblib.dump()